### ISSUE TITLE
Releases dropdown always contains an extra entry at the bottom

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-sphinx-theme#34] opened 2019-06-21 18:35 UTC
Right now, it's possible to pass an empty string or a list with an empty string to the `releases` command line option and nengo-sphinx-theme will generate links using that empty string. We should treat these cases as the same as not passing in a `releases` list.

**Comment by tbekolay** [comment] 2019-07-16 17:55
Actually, it turns out that regardless of how many releases there are, we always render an extra one at the bottom (see https://www.nengo.ai/nengo-sphinx-theme/v1.0.1/index.html )

**Comment by drasmuss** [comment] 2019-12-10 15:37
Also noticed that if you look at e.g. https://www.nengo.ai/nengo/v3.0.0/index.html there are two "3.0.0" entries in the dropdown.

**Comment by hunse** [comment] 2020-04-17 14:41
The empty entry is fixed in #58. @drasmuss found that the duplicate entries were specific to Nengo and caused by an extra commit for the 3.0.0 docs, so he fixed that manually.

**Closed as completed by hunse** 2020-04-17 14:41 UTC
